export const AUTHORIZATION_SERVICE = 'AUTHORIZATION_SERVICE'
export const SIGN_IN = 'SIGN_IN'
export const SIGN_UP = 'SIGN_UP'
export const GET_NEW_TOKEN = 'GET_NEW_TOKEN'
export const OAUTH_SIGN_IN = 'OAUTH_SIGN_IN'

export const UPDATE_USER = 'UPDATE_USER'
export const FIND_ONE_USER = 'FIND_ONE_USER'
export const AUTHENTICATION_SERVICE = 'AUTHENTICATION_SERVICE'
export const JWT_VERIFY = "JWT_VERIFY"
export const JWT_SIGN = "JWT_SIGN"