export const FIND_CHATTLING_ALL = "FIND_CHATTLING_ALL";
export const FIND_CHATTING_BY_ID = "FIND_CHATTING_BY_ID";
export const FIND_CHATTING_BY_ROOMID = "FIND_CHATTING_BY_ROOMID";
export const UPDATE_CHATTING = "UPDATE_CHATTING";
export const READ_CHATTING = "READ_CHATTING";
