server:
  port: 3000

db:
  type: 'mysql'
  host : 'svc.sel3.cloudtype.app'
  port: 30804
  username: 'root'
  password: 'root'
  database: 'kwangtalk'
  synchronize: true

jwt:
  expiresIn: 3600
  secret: 'bigkwangs'

redis:
  host : 'redis-19046.c245.us-east-1-3.ec2.cloud.redislabs.com'
  port: 19046
  password : 'ZmbYRRRGHNb7G4O9ew2VG9gm5P2SNI7u'

kakao:
  restApiKey: '7dd48b864b7c129d14f8f65cf429093b'
  secret: 'LjgAO0NAMk4XhenvumwOxlPacCJroBBG'
  redirectURL : 'http://localhost:3000/auth/kakao/login'

google:
  restApiKey: '846841962221-phpmlehpgrv1lj4ko9fkrmnalt3uo1fk.apps.googleusercontent.com'
  secret: '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'
  redirectURL : 'http://localhost:3000/auth/google/login'

naver:
  restApiKey: 'oTcoSe0Nvv4q6RaZyyAS'
  secret: 'YA_OXE1Knz'
  redirectURL : 'http://localhost:3000/auth/naver/login'