server:
  authenticationhost : "127.0.0.1"
  authenticationport : 3001
  authorizationhost : "127.0.0.1"
  authorizationport : 3002
  friendhost: "127.0.0.1"
  friendport: 3003
  chathost : "127.0.0.1"
  chatport : 3004
  roomhost: "127.0.0.1"
  roomport : 3005
  filehost: "127.0.0.1"
  fileport: 3006
  host : "127.0.0.1"
  port: 3000

log:
  loglevel : 'debug'
db:
  type: 'mysql'
  host : 'svc.sel3.cloudtype.app'
  port: 30804
  username: 'root'
  password: 'root'
  database: 'kwangtalk'
  synchronize: false

jwt:
  expiresIn: 3600
  secret: 'bigkwangs'

redis:
  host : 'redis-19046.c245.us-east-1-3.ec2.cloud.redislabs.com'
  port: 19046
  ttl : 60

kakao:
  restApiKey: '7dd48b864b7c129d14f8f65cf429093b'
  secret: 'LjgAO0NAMk4XhenvumwOxlPacCJroBBG'
  redirectURL : 'https://web-kakaotalk-frontend-eu1k2lllawv5vy.sel3.cloudtype.app/oauth'

google:
  restApiKey: '846841962221-phpmlehpgrv1lj4ko9fkrmnalt3uo1fk.apps.googleusercontent.com'
  secret: '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'
  redirectURL : 'https://web-kakaotalk-frontend-eu1k2lllawv5vy.sel3.cloudtype.app/oauth'

naver:
  restApiKey: 'oTcoSe0Nvv4q6RaZyyAS'
  secret: 'YA_OXE1Knz'
  redirectURL : 'https://web-kakaotalk-frontend-eu1k2lllawv5vy.sel3.cloudtype.app/oauth'

cors:
  frontendHost: 'https://web-kakaotalk-frontend-eu1k2lllawv5vy.sel3.cloudtype.app'

