db:
  type: 'mysql'
  host : '127.0.0.1'
  port: 13306
  username: 'root'
  password: 'root'
  database: 'kakaotalk'
  synchronize: true

jwt:
  secret: 'bigkwangs'


redis:
  host : '127.0.0.1'
  port: 6379

kakao:
  restApiKey: '7dd48b864b7c129d14f8f65cf429093b'
  secret: 'LjgAO0NAMk4XhenvumwOxlPacCJroBBG'
  getLoginURL : 'https://kauth.kakao.com/oauth/authorize'
  getTokenURL : 'https://kauth.kakao.com/oauth/token'
  getUserURL : 'https://kapi.kakao.com/v2/user/me'