db:
  type: 'mysql'
  host : '127.0.0.1'
  port: 13306
  username: 'root'
  password: 'root'
  database: 'kakaotalk'
  synchronize: true

jwt:
  secret: 'bigkwangs'


redis:
  host : '127.0.0.1'
  port: 6379
  ttl : 60

kakao:
  restApiKey: '7dd48b864b7c129d14f8f65cf429093b'
  secret: 'LjgAO0NAMk4XhenvumwOxlPacCJroBBG'
  redirectURL : 'http://localhost:3000/auth/kakao/login'

google:
  restApiKey: '846841962221-phpmlehpgrv1lj4ko9fkrmnalt3uo1fk.apps.googleusercontent.com'
  secret: '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'
  redirectURL : 'http://localhost:3000/auth/google/login'

naver:
  restApiKey: 'oTcoSe0Nvv4q6RaZyyAS'
  secret: 'YA_OXE1Knz'
  redirectURL : 'http://localhost:3000/auth/naver/login'

cors:
  frontendHost: 'http://localhost:3001'