server:
  port: 3000

db:
  type: 'mysql'
  host : 'svc.sel3.cloudtype.app'
  port: 30804
  username: 'root'
  password: 'root'
  database: 'kwangtalk'
  synchronize: true

jwt:
  expiresIn: 3600
  secret: 'bigkwangs'


kakao:
  restApiKey: '7dd48b864b7c129d14f8f65cf429093b'
  secret: 'LjgAO0NAMk4XhenvumwOxlPacCJroBBG'
  redirectURL : 'https://port-0-kakaotalk-backend-eu1k2lllawv5vy.sel3.cloudtype.app/auth/kakao/login'

google:
  restApiKey: '846841962221-phpmlehpgrv1lj4ko9fkrmnalt3uo1fk.apps.googleusercontent.com'
  secret: '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'
  redirectURL : 'https://port-0-kakaotalk-backend-eu1k2lllawv5vy.sel3.cloudtype.app/auth/google/login'

naver:
  restApiKey: 'oTcoSe0Nvv4q6RaZyyAS'
  secret: 'YA_OXE1Knz'
  redirectURL : 'https://port-0-kakaotalk-backend-eu1k2lllawv5vy.sel3.cloudtype.app/auth/naver/login'