server:
  port: 3000

db:
  type: 'mysql'
  host : 'svc.sel3.cloudtype.app'
  port: 32002
  username: 'root'
  password: 'root'
  database: 'kakaotalk'

jwt:
  expiresIn: 3600
  secret: 'bigkwangs'


kakao:
  restApiKey: '7dd48b864b7c129d14f8f65cf429093b'
  secret: 'LjgAO0NAMk4XhenvumwOxlPacCJroBBG'
  getLoginURL : 'https://kauth.kakao.com/oauth/authorize'
  getTokenURL : 'https://kauth.kakao.com/oauth/token'
  getUserURL : 'https://kapi.kakao.com/v2/user/me'