  secret: 'bigkwangs'

  server:
  port: 3000

db:
  type: 'mariadb'
  host : '127.0.0.1'
  port: 3306
  username: 'root'
  password: 'root'
  database: 'kakaotalk'

jwt:
  expiresIn: 3600
  secret: 'bigkwangs'