export const AUTHORIZATION_SERVICE = "AUTHORIZATION_SERVICE";
export const OAUTH_FACTORY_SERVICE = "OAUTH_FACTORY_SERVICE";
export const KAKAO_OAUTH = "KAKAO_OAUTH";
export const NAVER_OAUTH = "NAVER_OAUTH";
export const JWT_SERVICE = "JWT_SERVICE";
export const HTTP_SERVICE = "HTTP_SERVICE";
