version: '3'
services:
  local-redis:
    image: redis:latest
    container_name: local-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis/data:/data
    platform: linux/x86_64