name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17'  # Node.js 버전을 지정합니다.
    
    - name: Install Dependencies
      run: npm install  # 의존성을 설치합니다.
    
    - name: Run Script
      run: npm run start  # package.json에 정의된 스크립트를 실행합니다.
